apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.appName }}-secret-provider
spec:
  provider: aws
  parameters:
    region: {{ $.Values.region | default "eu-central-1" }}
    objects: |
      - objectName: {{ .Values.secrets.awsSecretName }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.secrets.keys }}
          - path: {{ . }}
            objectAlias: {{ . }}
          {{- end }}
  secretObjects:
    - secretName: {{ .Values.appName }}-secret
      type: Opaque
      data:
        {{- range .Values.secrets.keys }}
        - objectName: {{ . }}
          key: {{ . }}
        {{- end }}
