apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: {{ .Values.appName }}-serviceaccount
