apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: debug-container
      image: alpine:latest
      command: ["/bin/sh", "-c", "apk add --no-cache curl iputils && sleep infinity"]
      stdin: true
      tty: true
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
