apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app:  {{ .Values.appName }}
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "opentelemetry-operator-system/default"
    spec:
      containers:
        - name:  {{ .Values.appName }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}-secret

          ports:
            - containerPort: 3000

   