apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-nodeport-service
  labels:
    app: {{ .Values.appName }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 3000
