name: PR Build

permissions:
  id-token: write
  issues: write
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_cdk:
    uses: ./.github/workflows/deploy-cdk.yaml
    with:
      environment: stage
    secrets: inherit
  prepare_image_tag:
    runs-on: ubuntu-latest
    needs: deploy_cdk
    outputs:
      sanitized_branch: ${{ steps.sanitize.outputs.sanitized_branch }}
    steps:
      - name: Sanitize branch name
        id: sanitize
        run: |
          echo "sanitized_branch=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/[\/]/-/g' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
  pr-build:
    needs: prepare_image_tag
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: stage
      image_tag: pr-${{ needs.prepare_image_tag.outputs.sanitized_branch }}-${{ github.sha }}
