name: Stage Build

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy_cdk:
    uses: ./.github/workflows/deploy-cdk.yaml
    with:
      environment: stage
    secrets: inherit

  stage-build:
    needs: deploy_cdk
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: stage
      image_tag: ${{ github.sha }}
      tag_latest: true
